# Generated by Django 4.1 on 2022-08-22 04:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lead', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lead',
            old_name='assign_to',
            new_name='assigned_to',
        ),
    ]
